apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: open-dengue-data
type: Opaque
data:
  username: dXNlcjVUMA==    # user5T0 in base64
  password: STFBMzdTSHhsVGpCNnVsZg==    # I1A37SHxlTjB6ulf in base64
  database: c2FtcGxlZGI=    # sampledb in base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: open-dengue-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: open-dengue-data
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: open-dengue-data
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432