apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  namespace: open-dengue-data
spec:
  containers:
  - name: pg-client
    image: postgres:13
    command: ["sleep", "3600"]
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-password
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-user
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-name
  restartPolicy: Never