apiVersion: v1
kind: ConfigMap
metadata:
  name: dengue-api-config
  namespace: open-dengue-data
data:
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "sampledb"
  DB_USER: "user5T0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dengue-api
  namespace: open-dengue-data
  labels:
    app: dengue-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dengue-api
  template:
    metadata:
      labels:
        app: dengue-api
    spec:
      containers:
      - name: api
        image: dengue-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dengue-api-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dengue-api-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dengue-api-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: dengue-api-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dengue-api
  namespace: open-dengue-data
spec:
  selector:
    app: dengue-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP